name: Bug report
description: Create a report to help us improve
title: '[Bug] '
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        A clear and concise description of what the bug is.
  
  - type: input
    id: bug-summary
    attributes:
      label: Summary
      description: A brief summary of the bug.
      placeholder: Enter a brief summary of the bug.
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Description
      description: A detailed description of the bug.
      placeholder: Enter a detailed description of the bug.
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: The operating system where the bug occurred.
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: The browser where the bug occurred.
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true
